import { Approval, ConversationThread, ConversationThreadState, Prisma } from "@prisma/client";
import { prisma } from "@/lib/db";
import {
  buildAssetApprovalEmailCopy,
  buildFollowUpCopy,
  buildInitialOutreachCopy,
  buildThreadReplyTo,
  buildVisitApprovedMessage,
  sendConversationEmail,
} from "@/lib/conversation-email";
import { classifyCreatorReply, type CreatorReplyClassification } from "@/lib/conversation-classifier";

type StartAutomationInput = {
  creatorLeadIds?: string[];
  maxThreads?: number;
};

type ThreadMetadata = {
  brandName?: string;
  creatorName?: string;
  followUpCount?: number;
  maxFollowUps?: number;
  unsubscribe?: boolean;
  selectedTime?: string | null;
  assetNotes?: string | null;
  calendarActionRequired?: boolean;
  [key: string]: unknown;
};

const FOLLOW_UP_DELAY_MS = 3 * 24 * 60 * 60 * 1000;
const DEFAULT_MAX_FOLLOW_UPS = 2;
const CRON_BATCH_SIZE = 50;

export async function startCreatorOutreachAutomation(workspaceId: string, userId: string, input: StartAutomationInput = {}) {
  const take = Math.min(input.maxThreads ?? 50, 100);
  const leads = await prisma.creatorLead.findMany({
    where: {
      workspaceId,
      id: input.creatorLeadIds?.length ? { in: input.creatorLeadIds } : undefined,
      contactEmail: { not: null },
    },
    orderBy: [{ updatedAt: "desc" }, { createdAt: "desc" }],
    take,
    select: {
      id: true,
      displayName: true,
      handle: true,
      contactEmail: true,
      platform: true,
      profileUrl: true,
    },
  });

  const results = [];
  for (const lead of leads) {
    if (!lead.contactEmail) continue;

    // [Claude 2026-06-09] Compliance fix: never re-contact a creator who previously
    // unsubscribed (thread CLOSED) or declined (thread REJECTED). Opt-out is keyed on
    // the email address, so we check every thread for this email in the workspace, not
    // just the current lead's active thread. (A workspace-wide / global suppression
    // table would be a stronger follow-up, but this closes the immediate CAN-SPAM gap.)
    const suppressed = await prisma.conversationThread.findFirst({
      where: {
        workspaceId,
        creatorEmail: lead.contactEmail,
        state: { in: ["CLOSED", "REJECTED"] },
      },
      select: { id: true },
    });

    if (suppressed) {
      results.push({ threadId: suppressed.id, creatorEmail: lead.contactEmail, status: "suppressed" });
      continue;
    }

    const existing = await prisma.conversationThread.findFirst({
      where: {
        workspaceId,
        creatorLeadId: lead.id,
        state: { notIn: ["CLOSED", "REJECTED", "NO_RESPONSE"] },
      },
      orderBy: { createdAt: "desc" },
    });

    if (existing) {
      results.push({ threadId: existing.id, creatorEmail: lead.contactEmail, status: "existing" });
      continue;
    }

    const creatorName = lead.displayName || lead.handle || lead.contactEmail.split("@")[0];
    const brandName = await getWorkspaceBrandName(workspaceId);
    const draft = await prisma.outreachDraft.create({
      data: {
        workspaceId,
        createdById: userId,
        channel: "EMAIL",
        subject: `${brandName} creator collaboration invite`,
        body: "Initial outreach generated by Mako creator outreach automation.",
        status: "DRAFT",
        metadata: {
          automation: "creator-outreach",
          creatorLeadId: lead.id,
          safeAction: "approved-campaign-scope",
        },
      },
    });

    const thread = await prisma.conversationThread.create({
      data: {
        workspaceId,
        creatorLeadId: lead.id,
        outreachDraftId: draft.id,
        state: "READY_TO_SEND",
        subject: draft.subject,
        creatorEmail: lead.contactEmail,
        replyToEmail: buildThreadReplyTo("pending"),
        metadata: {
          brandName,
          creatorName,
          platform: lead.platform,
          profileUrl: lead.profileUrl,
          followUpCount: 0,
          maxFollowUps: DEFAULT_MAX_FOLLOW_UPS,
        },
      },
    });

    const updatedThread = await prisma.conversationThread.update({
      where: { id: thread.id },
      data: { replyToEmail: buildThreadReplyTo(thread.id) },
    });

    await sendInitialOutreach(updatedThread);
    results.push({ threadId: updatedThread.id, creatorEmail: lead.contactEmail, status: "sent" });
  }

  return { started: results.filter(result => result.status === "sent").length, results };
}

export async function sendInitialOutreach(thread: ConversationThread) {
  const metadata = getThreadMetadata(thread.metadata);
  const creatorName = metadata.creatorName || thread.creatorEmail?.split("@")[0] || "there";
  const brandName = metadata.brandName || "Mako Creator";
  if (!thread.creatorEmail) throw new Error("Thread has no creator email.");

  const copy = buildInitialOutreachCopy({ creatorName, brandName, threadId: thread.id });
  const email = await sendConversationEmail({ thread, to: thread.creatorEmail, subject: copy.subject, text: copy.text });
  await prisma.$transaction([
    prisma.conversationMessage.create({
      data: {
        threadId: thread.id,
        direction: "OUTBOUND",
        provider: email.provider,
        providerMessageId: email.providerMessageId,
        fromEmail: process.env.RESEND_FROM_EMAIL,
        toEmail: thread.creatorEmail,
        subject: copy.subject,
        textBody: copy.text,
        metadata: { automation: "initial-outreach" },
      },
    }),
    prisma.conversationThread.update({
      where: { id: thread.id },
      data: {
        state: "INITIAL_SENT",
        subject: copy.subject,
        nextActionAt: new Date(Date.now() + FOLLOW_UP_DELAY_MS),
        lastMessageAt: new Date(),
      },
    }),
  ]);
}

export async function processDueConversationThreads() {
  const now = new Date();
  const threads = await prisma.conversationThread.findMany({
    where: {
      nextActionAt: { lte: now },
      state: { in: ["INITIAL_SENT", "FOLLOW_UP_DUE"] },
    },
    orderBy: { nextActionAt: "asc" },
    take: CRON_BATCH_SIZE,
  });

  const results = [];
  for (const thread of threads) {
    const result = await processDueThread(thread);
    results.push(result);
  }
  return { processed: results.length, results };
}

async function processDueThread(thread: ConversationThread) {
  const metadata = getThreadMetadata(thread.metadata);
  const followUpCount = Number(metadata.followUpCount ?? 0);
  const maxFollowUps = Number(metadata.maxFollowUps ?? DEFAULT_MAX_FOLLOW_UPS);

  if (!thread.creatorEmail) {
    await moveThreadToHuman(thread, "Thread has no creator email for follow-up.");
    return { threadId: thread.id, status: "needs_human" };
  }

  if (followUpCount >= maxFollowUps) {
    await prisma.conversationThread.update({
      where: { id: thread.id },
      data: { state: "NO_RESPONSE", nextActionAt: null },
    });
    return { threadId: thread.id, status: "no_response" };
  }

  const creatorName = metadata.creatorName || thread.creatorEmail.split("@")[0];
  const brandName = metadata.brandName || "Mako Creator";
  const copy = buildFollowUpCopy({ creatorName, brandName, threadId: thread.id });
  const email = await sendConversationEmail({ thread, to: thread.creatorEmail, subject: copy.subject, text: copy.text });
  const nextMetadata = { ...metadata, followUpCount: followUpCount + 1 } satisfies ThreadMetadata;

  await prisma.$transaction([
    prisma.conversationMessage.create({
      data: {
        threadId: thread.id,
        direction: "OUTBOUND",
        provider: email.provider,
        providerMessageId: email.providerMessageId,
        fromEmail: process.env.RESEND_FROM_EMAIL,
        toEmail: thread.creatorEmail,
        subject: copy.subject,
        textBody: copy.text,
        metadata: { automation: "follow-up", followUpCount: followUpCount + 1 },
      },
    }),
    prisma.conversationThread.update({
      where: { id: thread.id },
      data: {
        state: "FOLLOW_UP_DUE",
        nextActionAt: new Date(Date.now() + FOLLOW_UP_DELAY_MS),
        lastMessageAt: new Date(),
        metadata: nextMetadata as Prisma.InputJsonValue,
      },
    }),
  ]);

  return { threadId: thread.id, status: "follow_up_sent", followUpCount: followUpCount + 1 };
}

export async function recordInboundCreatorReply(input: {
  threadId?: string | null;
  providerMessageId?: string | null;
  fromEmail?: string | null;
  toEmail?: string | null;
  subject?: string | null;
  textBody?: string | null;
  htmlBody?: string | null;
  metadata?: Prisma.InputJsonValue;
}) {
  const thread = await findInboundThread(input);
  if (!thread) throw new Error("Conversation thread not found for inbound email.");

  const text = input.textBody || stripHtml(input.htmlBody || "");
  const classification = await classifyCreatorReply({ subject: input.subject, text });

  await prisma.conversationMessage.create({
    data: {
      threadId: thread.id,
      direction: "INBOUND",
      provider: "resend",
      providerMessageId: input.providerMessageId,
      fromEmail: input.fromEmail,
      toEmail: input.toEmail,
      subject: input.subject,
      textBody: input.textBody,
      htmlBody: input.htmlBody,
      intent: classification.intent,
      confidence: classification.confidence,
      extractedTimes: classification.extractedTimes as Prisma.InputJsonValue,
      metadata: input.metadata ?? {},
    },
  });

  await advanceThreadFromClassification(thread.id, classification);
  return { threadId: thread.id, classification };
}

async function findInboundThread(input: { threadId?: string | null; toEmail?: string | null }) {
  if (input.threadId) {
    const byId = await prisma.conversationThread.findUnique({ where: { id: input.threadId } });
    if (byId) return byId;
  }

  const threadIdFromTo = extractThreadIdFromEmail(input.toEmail || "");
  if (threadIdFromTo) {
    const byReplyTo = await prisma.conversationThread.findUnique({ where: { id: threadIdFromTo } });
    if (byReplyTo) return byReplyTo;
  }

  if (input.toEmail) {
    return prisma.conversationThread.findFirst({ where: { replyToEmail: input.toEmail }, orderBy: { createdAt: "desc" } });
  }

  return null;
}

export async function advanceThreadFromClassification(threadId: string, classification: CreatorReplyClassification) {
  const thread = await prisma.conversationThread.findUnique({ where: { id: threadId } });
  if (!thread) throw new Error("Conversation thread not found.");

  const baseData = {
    lastIntent: classification.intent,
    lastConfidence: classification.confidence,
    nextActionAt: null,
    lastMessageAt: new Date(),
  };

  if (classification.needsHuman) {
    await moveThreadToHuman(thread, classification.summary, baseData);
    return;
  }

  if (classification.intent === "unsubscribe") {
    await prisma.conversationThread.update({
      where: { id: threadId },
      data: {
        ...baseData,
        state: "CLOSED",
        metadata: { ...getThreadMetadata(thread.metadata), unsubscribe: true } as Prisma.InputJsonValue,
      },
    });
    return;
  }

  if (classification.intent === "rejected") {
    await prisma.conversationThread.update({ where: { id: threadId }, data: { ...baseData, state: "REJECTED" } });
    return;
  }

  if (classification.intent === "interested_assets") {
    await createSensitiveActionApproval(thread, "SEND_ASSETS", classification.summary);
    await prisma.conversationThread.update({ where: { id: threadId }, data: { ...baseData, state: "WAITING_ASSET_APPROVAL" } });
    return;
  }

  if (classification.intent === "interested_visit") {
    await createSensitiveActionApproval(thread, "SCHEDULE_VISIT", classification.summary, { extractedTimes: classification.extractedTimes });
    await prisma.conversationThread.update({
      where: { id: threadId },
      data: {
        ...baseData,
        state: "WAITING_VISIT_APPROVAL",
        metadata: { ...getThreadMetadata(thread.metadata), extractedTimes: classification.extractedTimes } as Prisma.InputJsonValue,
      },
    });
    return;
  }

  await moveThreadToHuman(thread, classification.summary, baseData);
}

async function createSensitiveActionApproval(thread: ConversationThread, type: "SEND_ASSETS" | "SCHEDULE_VISIT", summary: string, extraMetadata: Record<string, unknown> = {}) {
  const createdById = await getWorkspaceOwnerId(thread.workspaceId);
  const title = type === "SEND_ASSETS" ? "Approve creator asset send" : "Approve creator visit scheduling";
  await prisma.approval.create({
    data: {
      workspaceId: thread.workspaceId,
      createdById,
      outreachDraftId: thread.outreachDraftId,
      type,
      title,
      summary,
      riskLevel: type === "SCHEDULE_VISIT" ? "HIGH" : "MEDIUM",
      metadata: {
        automation: "creator-outreach",
        threadId: thread.id,
        creatorEmail: thread.creatorEmail,
        ...extraMetadata,
      } as Prisma.InputJsonValue,
    },
  });
}

export async function handleApprovedConversationApproval(approval: Approval) {
  if (approval.status !== "APPROVED") return null;
  if (approval.type !== "SEND_ASSETS" && approval.type !== "SCHEDULE_VISIT") return null;

  const metadata = asRecord(approval.metadata);
  const threadId = typeof metadata.threadId === "string" ? metadata.threadId : null;
  if (!threadId) return null;
  const thread = await prisma.conversationThread.findFirst({ where: { id: threadId, workspaceId: approval.workspaceId } });
  if (!thread || !thread.creatorEmail) return null;

  // [Claude 2026-06-09] Idempotency guard (defense in depth): if the thread has already
  // reached the terminal state for this action, do not send the creator a second email.
  if (approval.type === "SEND_ASSETS") {
    if (thread.state === "ASSETS_SENT") return { threadId: thread.id, action: "already_sent" };
    return sendApprovedAssets(thread);
  }

  if (thread.state === "VISIT_SCHEDULED") return { threadId: thread.id, action: "already_scheduled" };
  return markVisitApproved(thread, metadata.selectedTime ? String(metadata.selectedTime) : null);
}

async function sendApprovedAssets(thread: ConversationThread) {
  const metadata = getThreadMetadata(thread.metadata);
  const creatorName = metadata.creatorName || thread.creatorEmail?.split("@")[0] || "there";
  const brandName = metadata.brandName || "Mako Creator";
  const copy = buildAssetApprovalEmailCopy({ creatorName, brandName, threadId: thread.id });
  const email = await sendConversationEmail({ thread, to: thread.creatorEmail!, subject: copy.subject, text: copy.text });

  await prisma.$transaction([
    prisma.conversationMessage.create({
      data: {
        threadId: thread.id,
        direction: "OUTBOUND",
        provider: email.provider,
        providerMessageId: email.providerMessageId,
        fromEmail: process.env.RESEND_FROM_EMAIL,
        toEmail: thread.creatorEmail,
        subject: copy.subject,
        textBody: copy.text,
        metadata: { automation: "approved-assets" },
      },
    }),
    prisma.conversationThread.update({ where: { id: thread.id }, data: { state: "ASSETS_SENT", lastMessageAt: new Date(), nextActionAt: null } }),
  ]);
  return { threadId: thread.id, action: "assets_sent" };
}

async function markVisitApproved(thread: ConversationThread, selectedTime: string | null) {
  const metadata = getThreadMetadata(thread.metadata);
  const creatorName = metadata.creatorName || thread.creatorEmail?.split("@")[0] || "there";
  const brandName = metadata.brandName || "Mako Creator";
  const copy = buildVisitApprovedMessage({ creatorName, brandName, selectedTime, threadId: thread.id });
  const email = await sendConversationEmail({ thread, to: thread.creatorEmail!, subject: copy.subject, text: copy.text });

  await prisma.$transaction([
    prisma.conversationMessage.create({
      data: {
        threadId: thread.id,
        direction: "OUTBOUND",
        provider: email.provider,
        providerMessageId: email.providerMessageId,
        fromEmail: process.env.RESEND_FROM_EMAIL,
        toEmail: thread.creatorEmail,
        subject: copy.subject,
        textBody: copy.text,
        metadata: { automation: "approved-visit", selectedTime, calendarActionRequired: true },
      },
    }),
    prisma.conversationThread.update({
      where: { id: thread.id },
      data: {
        state: "VISIT_SCHEDULED",
        lastMessageAt: new Date(),
        nextActionAt: null,
        metadata: { ...metadata, selectedTime, calendarActionRequired: true } as Prisma.InputJsonValue,
      },
    }),
  ]);
  return { threadId: thread.id, action: "visit_confirmed", calendarActionRequired: true };
}

async function moveThreadToHuman(thread: ConversationThread, reason: string, extraData: Partial<{ lastIntent: string; lastConfidence: number; nextActionAt: null; lastMessageAt: Date }> = {}) {
  const humanId = await getWorkspaceOwnerId(thread.workspaceId);
  await prisma.$transaction([
    prisma.conversationThread.update({
      where: { id: thread.id },
      data: {
        ...extraData,
        state: "NEEDS_HUMAN",
        assignedHumanId: humanId,
        nextActionAt: null,
      },
    }),
    prisma.dashboardTask.create({
      data: {
        workspaceId: thread.workspaceId,
        createdById: humanId,
        title: "Review creator reply",
        description: reason,
        type: "OUTREACH",
        priority: 8,
        metadata: { automation: "creator-outreach", threadId: thread.id } as Prisma.InputJsonValue,
      },
    }),
  ]);
}

async function getWorkspaceOwnerId(workspaceId: string) {
  const owner = await prisma.workspaceMember.findFirst({
    where: { workspaceId, role: { in: ["OWNER", "ADMIN"] } },
    orderBy: { createdAt: "asc" },
    select: { userId: true },
  });
  if (!owner) throw new Error("Workspace owner not found for conversation automation.");
  return owner.userId;
}

async function getWorkspaceBrandName(workspaceId: string) {
  const workspace = await prisma.workspace.findUnique({ where: { id: workspaceId }, select: { name: true } });
  return workspace?.name || "Mako Creator";
}

function getThreadMetadata(value: Prisma.JsonValue): ThreadMetadata {
  return asRecord(value) as ThreadMetadata;
}

function asRecord(value: Prisma.JsonValue | unknown): Record<string, unknown> {
  return Boolean(value) && typeof value === "object" && !Array.isArray(value) ? value as Record<string, unknown> : {};
}

function extractThreadIdFromEmail(email: string) {
  const match = email.match(/thread\+([^@\s]+)@/i);
  return match?.[1] || null;
}

function stripHtml(html: string) {
  return html.replace(/<style[\s\S]*?<\/style>/gi, " ")
    .replace(/<script[\s\S]*?<\/script>/gi, " ")
    .replace(/<[^>]+>/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}
