import { Approval, ConversationThread, ConversationThreadState, Prisma } from "@prisma/client";
import { UserFacingError } from "@/lib/api";
import { prisma } from "@/lib/db";
import {
  buildAssetApprovalEmailCopy,
  buildFollowUpCopy,
  buildThreadReplyTo,
  buildUnsubscribeUrl,
  sendConversationEmail,
} from "@/lib/conversation-email";
import { classifyCreatorReply, type CreatorReplyClassification } from "@/lib/conversation-classifier";
import { buildAnchoredOutreach, getCreatorOutreachContext, type OutreachCopy } from "@/lib/outreach-copy";

type StartAutomationInput = {
  creatorLeadIds?: string[];
  maxThreads?: number;
  firstMessage?: OutreachCopy; // [Claude 2026-06-10] human-previewed copy to send as the first touch
  campaignId?: string; // [Claude 2026-06-16] which campaign this outreach belongs to
};

type ThreadMetadata = {
  brandName?: string;
  creatorName?: string;
  followUpCount?: number;
  maxFollowUps?: number;
  unsubscribe?: boolean;
  selectedTime?: string | null;
  assetNotes?: string | null;
  calendarActionRequired?: boolean;
  [key: string]: unknown;
};

const FOLLOW_UP_DELAY_MS = 3 * 24 * 60 * 60 * 1000;
const DEFAULT_MAX_FOLLOW_UPS = 2;
const CRON_BATCH_SIZE = 50;

export async function startCreatorOutreachAutomation(workspaceId: string, userId: string, input: StartAutomationInput = {}) {
  const take = Math.min(input.maxThreads ?? 50, 100);
  const leads = await prisma.creatorLead.findMany({
    where: {
      workspaceId,
      id: input.creatorLeadIds?.length ? { in: input.creatorLeadIds } : undefined,
      contactEmail: { not: null },
    },
    orderBy: [{ updatedAt: "desc" }, { createdAt: "desc" }],
    take,
    select: {
      id: true,
      displayName: true,
      handle: true,
      contactEmail: true,
      platform: true,
      profileUrl: true,
    },
  });

  // [Claude 2026-06-10] L5: brand name is per-workspace, not per-lead — fetch once.
  const brandName = await getWorkspaceBrandName(workspaceId);

  const results = [];
  for (const lead of leads) {
    if (!lead.contactEmail) continue;

    // [Claude 2026-06-09] Compliance fix: never re-contact a creator who previously
    // unsubscribed (thread CLOSED) or declined (thread REJECTED). Opt-out is keyed on
    // the email address, so we check every thread for this email in the workspace, not
    // just the current lead's active thread. (A workspace-wide / global suppression
    // table would be a stronger follow-up, but this closes the immediate CAN-SPAM gap.)
    const suppressed = await prisma.conversationThread.findFirst({
      where: {
        workspaceId,
        creatorEmail: lead.contactEmail,
        state: { in: ["CLOSED", "REJECTED"] },
      },
      select: { id: true },
    });

    if (suppressed) {
      results.push({ threadId: suppressed.id, creatorEmail: lead.contactEmail, status: "suppressed" });
      continue;
    }

    const existing = await prisma.conversationThread.findFirst({
      where: {
        workspaceId,
        creatorLeadId: lead.id,
        state: { notIn: ["CLOSED", "REJECTED", "NO_RESPONSE"] },
      },
      orderBy: { createdAt: "desc" },
    });

    if (existing) {
      results.push({ threadId: existing.id, creatorEmail: lead.contactEmail, status: "existing" });
      continue;
    }

    const creatorName = lead.displayName || lead.handle || lead.contactEmail.split("@")[0];
    const draft = await prisma.outreachDraft.create({
      data: {
        workspaceId,
        createdById: userId,
        channel: "EMAIL",
        subject: `${brandName} creator collaboration invite`,
        body: "Initial outreach generated by Mako creator outreach automation.",
        status: "DRAFT",
        metadata: {
          automation: "creator-outreach",
          creatorLeadId: lead.id,
          safeAction: "approved-campaign-scope",
        },
      },
    });

    const thread = await prisma.conversationThread.create({
      data: {
        workspaceId,
        creatorLeadId: lead.id,
        outreachDraftId: draft.id,
        campaignId: input.campaignId ?? null,
        state: "READY_TO_SEND",
        subject: draft.subject,
        creatorEmail: lead.contactEmail,
        replyToEmail: buildThreadReplyTo("pending"),
        metadata: {
          brandName,
          creatorName,
          platform: lead.platform,
          profileUrl: lead.profileUrl,
          followUpCount: 0,
          maxFollowUps: DEFAULT_MAX_FOLLOW_UPS,
        },
      },
    });

    const updatedThread = await prisma.conversationThread.update({
      where: { id: thread.id },
      data: { replyToEmail: buildThreadReplyTo(thread.id) },
    });

    // [Claude 2026-06-10] Apply the human-previewed copy only when this is a single,
    // explicitly-approved creator (so a batch start can't reuse one override for everyone).
    await sendInitialOutreach(updatedThread, leads.length === 1 ? input.firstMessage : undefined);
    results.push({ threadId: updatedThread.id, creatorEmail: lead.contactEmail, status: "sent" });
  }

  return { started: results.filter(result => result.status === "sent").length, results };
}

export async function sendInitialOutreach(thread: ConversationThread, override?: OutreachCopy) {
  if (!thread.creatorEmail) throw new Error("Thread has no creator email.");
  const metadata = getThreadMetadata(thread.metadata);

  // [Claude 2026-06-10] Feature 4: anchor the opener on a real signal about this creator
  // (human style note → niche/city fallback). `override` is the human-previewed copy.
  const context = await getCreatorOutreachContext(thread.workspaceId, thread.creatorLeadId);
  const copy: OutreachCopy = context
    ? await buildAnchoredOutreach(context, override)
    : override ?? {
        subject: `${metadata.brandName || "Mako Creator"} creator collaboration invite`,
        body: `Hi ${metadata.creatorName || thread.creatorEmail.split("@")[0]},\n\nI'm reaching out from ${metadata.brandName || "Mako Creator"} about a possible creator collaboration. If you're open to it, just reply and let me know.`,
      };

  const text = `${copy.body}\n\nUnsubscribe: ${buildUnsubscribeUrl(thread.id)}`;
  const email = await sendConversationEmail({ thread, to: thread.creatorEmail, subject: copy.subject, text });
  await prisma.$transaction([
    prisma.conversationMessage.create({
      data: {
        threadId: thread.id,
        direction: "OUTBOUND",
        provider: email.provider,
        providerMessageId: email.providerMessageId,
        fromEmail: process.env.RESEND_FROM_EMAIL,
        toEmail: thread.creatorEmail,
        subject: copy.subject,
        textBody: text,
        metadata: { automation: "initial-outreach", anchored: Boolean(override || context?.styleNote) },
      },
    }),
    prisma.conversationThread.update({
      where: { id: thread.id },
      data: {
        state: "INITIAL_SENT",
        subject: copy.subject,
        nextActionAt: new Date(Date.now() + FOLLOW_UP_DELAY_MS),
        lastMessageAt: new Date(),
      },
    }),
  ]);
}

export async function processDueConversationThreads() {
  const now = new Date();
  const threads = await prisma.conversationThread.findMany({
    where: {
      nextActionAt: { lte: now },
      state: { in: ["INITIAL_SENT", "FOLLOW_UP_DUE"] },
    },
    orderBy: { nextActionAt: "asc" },
    take: CRON_BATCH_SIZE,
  });

  // [Claude 2026-06-10] M4 fix: isolate failures per thread. Previously one failed
  // send threw out of the loop, 500ing the whole cron run and starving every thread
  // behind the broken one (and the batch would retry from scratch next run).
  const results = [];
  for (const thread of threads) {
    try {
      const result = await processDueThread(thread);
      results.push(result);
    } catch (error) {
      console.error(`Cron: processing thread ${thread.id} failed`, error);
      results.push({ threadId: thread.id, status: "error" as const });
    }
  }
  return { processed: results.length, results };
}

async function processDueThread(thread: ConversationThread) {
  const metadata = getThreadMetadata(thread.metadata);
  const followUpCount = Number(metadata.followUpCount ?? 0);
  const maxFollowUps = Number(metadata.maxFollowUps ?? DEFAULT_MAX_FOLLOW_UPS);

  if (!thread.creatorEmail) {
    await moveThreadToHuman(thread, "Thread has no creator email for follow-up.");
    return { threadId: thread.id, status: "needs_human" };
  }

  if (followUpCount >= maxFollowUps) {
    await prisma.conversationThread.update({
      where: { id: thread.id },
      data: { state: "NO_RESPONSE", nextActionAt: null },
    });
    return { threadId: thread.id, status: "no_response" };
  }

  const creatorName = metadata.creatorName || thread.creatorEmail.split("@")[0];
  const brandName = metadata.brandName || "Mako Creator";
  const copy = buildFollowUpCopy({ creatorName, brandName, threadId: thread.id });
  const email = await sendConversationEmail({ thread, to: thread.creatorEmail, subject: copy.subject, text: copy.text });
  const nextMetadata = { ...metadata, followUpCount: followUpCount + 1 } satisfies ThreadMetadata;

  await prisma.$transaction([
    prisma.conversationMessage.create({
      data: {
        threadId: thread.id,
        direction: "OUTBOUND",
        provider: email.provider,
        providerMessageId: email.providerMessageId,
        fromEmail: process.env.RESEND_FROM_EMAIL,
        toEmail: thread.creatorEmail,
        subject: copy.subject,
        textBody: copy.text,
        metadata: { automation: "follow-up", followUpCount: followUpCount + 1 },
      },
    }),
    prisma.conversationThread.update({
      where: { id: thread.id },
      data: {
        state: "FOLLOW_UP_DUE",
        nextActionAt: new Date(Date.now() + FOLLOW_UP_DELAY_MS),
        lastMessageAt: new Date(),
        metadata: nextMetadata as Prisma.InputJsonValue,
      },
    }),
  ]);

  return { threadId: thread.id, status: "follow_up_sent", followUpCount: followUpCount + 1 };
}

export async function recordInboundCreatorReply(input: {
  threadId?: string | null;
  providerMessageId?: string | null;
  fromEmail?: string | null;
  toEmail?: string | null;
  subject?: string | null;
  textBody?: string | null;
  htmlBody?: string | null;
  metadata?: Prisma.InputJsonValue;
}) {
  const thread = await findInboundThread(input);
  // [Claude 2026-06-11] 404 with a specific message so test emails to nonexistent
  // threads are distinguishable from real failures in Resend's webhook logs.
  if (!thread) throw new UserFacingError("No conversation thread matches this inbound email (signature was valid).", 404);

  // [Claude 2026-06-10] Security fix (H1): thread routing (X-Mako-Thread-ID header and
  // the to-address) is fully controlled by the external sender, so it must not be trusted
  // alone. Verify the sender is the creator on this thread before running any automation.
  // On mismatch we quarantine: record the message for audit + surface a human task, but
  // never touch the thread state machine (no unsubscribe/reject/approval side effects).
  const fromEmail = input.fromEmail?.trim().toLowerCase() || null;
  const expectedEmail = thread.creatorEmail?.trim().toLowerCase() || null;
  const senderVerified = Boolean(fromEmail && expectedEmail && fromEmail === expectedEmail);

  if (!senderVerified) {
    const ownerId = await getWorkspaceOwnerId(thread.workspaceId);
    await prisma.$transaction([
      prisma.conversationMessage.create({
        data: {
          threadId: thread.id,
          direction: "INBOUND",
          provider: "resend",
          providerMessageId: input.providerMessageId,
          fromEmail: input.fromEmail,
          toEmail: input.toEmail,
          subject: input.subject,
          textBody: input.textBody,
          htmlBody: input.htmlBody,
          intent: "unclear",
          metadata: { ...asRecord(input.metadata), senderMismatch: true, quarantined: true } as Prisma.InputJsonValue,
        },
      }),
      prisma.dashboardTask.create({
        data: {
          workspaceId: thread.workspaceId,
          createdById: ownerId,
          title: "Review quarantined inbound email",
          description: `An inbound email for this thread came from "${input.fromEmail || "unknown sender"}", which does not match the creator on file (${thread.creatorEmail || "none"}). No automated action was taken.`,
          type: "OUTREACH",
          priority: 8,
          metadata: { automation: "creator-outreach", threadId: thread.id, senderMismatch: true } as Prisma.InputJsonValue,
        },
      }),
    ]);
    return { threadId: thread.id, quarantined: true as const };
  }

  const text = input.textBody || stripHtml(input.htmlBody || "");
  const classification = await classifyCreatorReply({ subject: input.subject, text });

  await prisma.conversationMessage.create({
    data: {
      threadId: thread.id,
      direction: "INBOUND",
      provider: "resend",
      providerMessageId: input.providerMessageId,
      fromEmail: input.fromEmail,
      toEmail: input.toEmail,
      subject: input.subject,
      textBody: input.textBody,
      htmlBody: input.htmlBody,
      intent: classification.intent,
      confidence: classification.confidence,
      extractedTimes: classification.extractedTimes as Prisma.InputJsonValue,
      metadata: input.metadata ?? {},
    },
  });

  await advanceThreadFromClassification(thread.id, classification);
  return { threadId: thread.id, classification };
}

async function findInboundThread(input: { threadId?: string | null; toEmail?: string | null; fromEmail?: string | null }) {
  if (input.threadId) {
    const byId = await prisma.conversationThread.findUnique({ where: { id: input.threadId } });
    if (byId) return byId;
  }

  // Legacy thread+<id>@ addresses on emails sent before the clean reply address.
  const threadIdFromTo = extractThreadIdFromEmail(input.toEmail || "");
  if (threadIdFromTo) {
    const byReplyTo = await prisma.conversationThread.findUnique({ where: { id: threadIdFromTo } });
    if (byReplyTo) return byReplyTo;
  }

  // [Claude 2026-06-12] Primary routing for the clean reply address: a reply belongs
  // to the sender's most recent thread. (The old replyToEmail-equality fallback was
  // removed — every thread now shares one reply address, so it would mis-route.)
  const fromEmail = input.fromEmail?.trim().toLowerCase();
  if (fromEmail) {
    const bySender = await prisma.conversationThread.findFirst({
      where: { creatorEmail: fromEmail },
      orderBy: [{ lastMessageAt: { sort: "desc", nulls: "last" } }, { createdAt: "desc" }],
    });
    if (bySender) return bySender;
  }

  return null;
}

export async function advanceThreadFromClassification(threadId: string, classification: CreatorReplyClassification) {
  const thread = await prisma.conversationThread.findUnique({ where: { id: threadId } });
  if (!thread) throw new Error("Conversation thread not found.");

  const baseData = {
    lastIntent: classification.intent,
    lastConfidence: classification.confidence,
    nextActionAt: null,
    lastMessageAt: new Date(),
  };

  if (classification.needsHuman) {
    await moveThreadToHuman(thread, classification.summary, baseData);
    return;
  }

  if (classification.intent === "unsubscribe") {
    await prisma.conversationThread.update({
      where: { id: threadId },
      data: {
        ...baseData,
        state: "CLOSED",
        metadata: { ...getThreadMetadata(thread.metadata), unsubscribe: true } as Prisma.InputJsonValue,
      },
    });
    return;
  }

  if (classification.intent === "rejected") {
    await prisma.conversationThread.update({ where: { id: threadId }, data: { ...baseData, state: "REJECTED" } });
    return;
  }

  if (classification.intent === "interested_assets") {
    await createSensitiveActionApproval(thread, "SEND_ASSETS", classification.summary);
    await prisma.conversationThread.update({ where: { id: threadId }, data: { ...baseData, state: "WAITING_ASSET_APPROVAL" } });
    return;
  }

  if (classification.intent === "interested_visit") {
    await createSensitiveActionApproval(thread, "SCHEDULE_VISIT", classification.summary, { extractedTimes: classification.extractedTimes });
    await prisma.conversationThread.update({
      where: { id: threadId },
      data: {
        ...baseData,
        state: "WAITING_VISIT_APPROVAL",
        metadata: { ...getThreadMetadata(thread.metadata), extractedTimes: classification.extractedTimes } as Prisma.InputJsonValue,
      },
    });
    return;
  }

  await moveThreadToHuman(thread, classification.summary, baseData);
}

async function createSensitiveActionApproval(thread: ConversationThread, type: "SEND_ASSETS" | "SCHEDULE_VISIT", summary: string, extraMetadata: Record<string, unknown> = {}) {
  const createdById = await getWorkspaceOwnerId(thread.workspaceId);
  const title = type === "SEND_ASSETS" ? "Approve creator asset send" : "Approve creator visit scheduling";
  await prisma.approval.create({
    data: {
      workspaceId: thread.workspaceId,
      createdById,
      outreachDraftId: thread.outreachDraftId,
      type,
      title,
      summary,
      riskLevel: type === "SCHEDULE_VISIT" ? "HIGH" : "MEDIUM",
      metadata: {
        automation: "creator-outreach",
        threadId: thread.id,
        creatorEmail: thread.creatorEmail,
        ...extraMetadata,
      } as Prisma.InputJsonValue,
    },
  });
}

export async function handleApprovedConversationApproval(approval: Approval) {
  if (approval.status !== "APPROVED") return null;
  if (approval.type !== "SEND_ASSETS" && approval.type !== "SCHEDULE_VISIT") return null;

  const metadata = asRecord(approval.metadata);
  const threadId = typeof metadata.threadId === "string" ? metadata.threadId : null;
  if (!threadId) return null;
  const thread = await prisma.conversationThread.findFirst({ where: { id: threadId, workspaceId: approval.workspaceId } });
  if (!thread || !thread.creatorEmail) return null;

  // [Claude 2026-06-09] Idempotency guard (defense in depth): if the thread has already
  // reached the terminal state for this action, do not send the creator a second email.
  if (approval.type === "SEND_ASSETS") {
    if (thread.state === "ASSETS_SENT") return { threadId: thread.id, action: "already_sent" };
    return sendApprovedAssets(thread);
  }

  if (thread.state === "VISIT_SCHEDULED") return { threadId: thread.id, action: "already_scheduled" };
  return markVisitApproved(thread, metadata.selectedTime ? String(metadata.selectedTime) : null);
}

// [Claude 2026-06-10] Give "Need Change" and "Reject" real effects. Previously these
// statuses did nothing, leaving the conversation thread stuck in a WAITING_* state with
// no pending approval and no human notified. Now we route the thread back to a human with
// a dashboard task explaining the decision.
export async function handleReviewedConversationApproval(approval: Approval) {
  if (approval.status !== "NEEDS_CHANGES" && approval.status !== "REJECTED") return null;
  if (approval.type !== "SEND_ASSETS" && approval.type !== "SCHEDULE_VISIT") return null;

  const metadata = asRecord(approval.metadata);
  const threadId = typeof metadata.threadId === "string" ? metadata.threadId : null;
  if (!threadId) return null;

  const thread = await prisma.conversationThread.findFirst({ where: { id: threadId, workspaceId: approval.workspaceId } });
  if (!thread) return null;

  // Only act on threads still waiting on this approval; don't disturb ones already moved on.
  if (thread.state !== "WAITING_ASSET_APPROVAL" && thread.state !== "WAITING_VISIT_APPROVAL") return null;

  const reason = approval.status === "REJECTED"
    ? `Approval rejected by a human: "${approval.title}". Decide the next step with this creator${approval.decisionNotes ? ` — notes: ${approval.decisionNotes}` : "."}`
    : `Approval needs changes: "${approval.title}". Revise before resubmitting${approval.decisionNotes ? ` — notes: ${approval.decisionNotes}` : "."}`;

  await moveThreadToHuman(thread, reason);
  return { threadId: thread.id, action: approval.status === "REJECTED" ? "rejected_to_human" : "needs_changes_to_human" };
}

async function sendApprovedAssets(thread: ConversationThread) {
  const metadata = getThreadMetadata(thread.metadata);
  const creatorName = metadata.creatorName || thread.creatorEmail?.split("@")[0] || "there";
  const brandName = metadata.brandName || "Mako Creator";
  const copy = buildAssetApprovalEmailCopy({ creatorName, brandName, threadId: thread.id });
  const email = await sendConversationEmail({ thread, to: thread.creatorEmail!, subject: copy.subject, text: copy.text });

  await prisma.$transaction([
    prisma.conversationMessage.create({
      data: {
        threadId: thread.id,
        direction: "OUTBOUND",
        provider: email.provider,
        providerMessageId: email.providerMessageId,
        fromEmail: process.env.RESEND_FROM_EMAIL,
        toEmail: thread.creatorEmail,
        subject: copy.subject,
        textBody: copy.text,
        metadata: { automation: "approved-assets" },
      },
    }),
    prisma.conversationThread.update({ where: { id: thread.id }, data: { state: "ASSETS_SENT", lastMessageAt: new Date(), nextActionAt: null } }),
  ]);
  return { threadId: thread.id, action: "assets_sent" };
}

// [Claude 2026-06-13] Visit confirmation email to creator removed per product decision:
// the calendar invite (sent separately from Inbox) already signals confirmed intent.
// This function now only advances the thread state — no outbound email to the creator.
async function markVisitApproved(thread: ConversationThread, selectedTime: string | null) {
  const metadata = getThreadMetadata(thread.metadata);
  await prisma.conversationThread.update({
    where: { id: thread.id },
    data: {
      state: "VISIT_SCHEDULED",
      lastMessageAt: new Date(),
      nextActionAt: null,
      metadata: { ...metadata, selectedTime, calendarActionRequired: false } as Prisma.InputJsonValue,
    },
  });
  return { threadId: thread.id, action: "visit_confirmed" };
}

async function moveThreadToHuman(thread: ConversationThread, reason: string, extraData: Partial<{ lastIntent: string; lastConfidence: number; nextActionAt: null; lastMessageAt: Date }> = {}) {
  const humanId = await getWorkspaceOwnerId(thread.workspaceId);
  await prisma.$transaction([
    prisma.conversationThread.update({
      where: { id: thread.id },
      data: {
        ...extraData,
        state: "NEEDS_HUMAN",
        assignedHumanId: humanId,
        nextActionAt: null,
      },
    }),
    prisma.dashboardTask.create({
      data: {
        workspaceId: thread.workspaceId,
        createdById: humanId,
        title: "Review creator reply",
        description: reason,
        type: "OUTREACH",
        priority: 8,
        metadata: { automation: "creator-outreach", threadId: thread.id } as Prisma.InputJsonValue,
      },
    }),
  ]);
}

async function getWorkspaceOwnerId(workspaceId: string) {
  const owner = await prisma.workspaceMember.findFirst({
    where: { workspaceId, role: { in: ["OWNER", "ADMIN"] } },
    orderBy: { createdAt: "asc" },
    select: { userId: true },
  });
  if (!owner) throw new Error("Workspace owner not found for conversation automation.");
  return owner.userId;
}

async function getWorkspaceBrandName(workspaceId: string) {
  const workspace = await prisma.workspace.findUnique({ where: { id: workspaceId }, select: { name: true } });
  return workspace?.name || "Mako Creator";
}

function getThreadMetadata(value: Prisma.JsonValue): ThreadMetadata {
  return asRecord(value) as ThreadMetadata;
}

function asRecord(value: Prisma.JsonValue | unknown): Record<string, unknown> {
  return Boolean(value) && typeof value === "object" && !Array.isArray(value) ? value as Record<string, unknown> : {};
}

function extractThreadIdFromEmail(email: string) {
  const match = email.match(/thread\+([^@\s]+)@/i);
  return match?.[1] || null;
}

function stripHtml(html: string) {
  return html.replace(/<style[\s\S]*?<\/style>/gi, " ")
    .replace(/<script[\s\S]*?<\/script>/gi, " ")
    .replace(/<[^>]+>/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}
